import * as lancedb from '@lancedb/lancedb'
import { createHash } from 'node:crypto'
import { promises as fs } from 'node:fs'
import path from 'node:path'
import ts from 'typescript'
import { fileURLToPath } from 'node:url'

const ROOT_DIR = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const LANCEDB_DIR = path.join(ROOT_DIR, '.lancedb')
const CODE_INDEX_DIR = path.join(ROOT_DIR, '.code-index')
const SYNC_STATE_PATH = path.join(CODE_INDEX_DIR, 'sync-state.json')

const TABLE_NAME = 'code_chunks'
const OLLAMA_URL = process.env.OLLAMA_URL ?? 'http://localhost:11434'
const OLLAMA_EMBED_MODEL = process.env.OLLAMA_EMBED_MODEL ?? 'nomic-embed-text'
const MAX_CHUNK_CHARS = 3_500
const OVERLAP_LINES = 8
const SEARCH_LIMIT = 5
const VECTOR_CANDIDATE_LIMIT = 12

const SCAN_ROOTS = ['src', 'party', 'server', 'backend', 'shared', 'common']
const IGNORED_DIRS = new Set([
  'node_modules',
  'dist',
  'build',
  '.next',
  'coverage',
  '.git',
  '.lancedb',
  '.code-index',
])

type IndexedLanguage = 'typescript' | 'json' | 'markdown'
type ChunkType =
  | 'summary'
  | 'function'
  | 'component'
  | 'hook'
  | 'class'
  | 'type'
  | 'const'
  | 'object_method'
  | 'json'
  | 'file'

interface SyncFileState {
  hash: string
  chunkIds: string[]
  indexedAt: string
}

interface SyncState {
  version: 1
  files: Record<string, SyncFileState>
}

interface CodeChunk {
  content: string
  startLine: number
  endLine: number
  symbolName: string
  chunkType: ChunkType
  language: IndexedLanguage
  imports?: string[]
}

interface LanceCodeRecord {
  id: string
  vector: number[]
  file_path: string
  file_hash: string
  chunk_index: number
  language: IndexedLanguage
  start_line: number
  end_line: number
  symbol_name: string
  chunk_type: ChunkType
  imports?: string
  content: string
}

export interface CodeSearchResult {
  score: number
  source: 'keyword' | 'vector'
  file_path: string
  start_line: number
  end_line: number
  chunk_index: number
  symbol_name: string
  chunk_type: ChunkType
  imports: string[]
  content: string
}

function toProjectPath(filePath: string): string {
  return path.relative(ROOT_DIR, filePath).split(path.sep).join('/')
}

function sha256(content: string): string {
  return createHash('sha256').update(content).digest('hex')
}

function isGeneratedFile(filePath: string, content?: string): boolean {
  const normalized = filePath.split(path.sep).join('/')
  const basename = path.basename(filePath)

  if (
    normalized.includes('/generated/') ||
    normalized.includes('/__generated__/') ||
    /\.(generated|gen)\.(ts|tsx|json|md|mdx)$/.test(basename) ||
    basename.endsWith('.d.ts')
  ) {
    return true
  }

  if (!content) return false

  const firstLines = content.split(/\r?\n/, 5).join('\n').toLowerCase()
  return (
    firstLines.includes('@generated') ||
    firstLines.includes('auto-generated') ||
    firstLines.includes('autogenerated') ||
    firstLines.includes('do not edit')
  )
}

async function pathExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath)
    return true
  } catch {
    return false
  }
}

async function scanDirectory(dir: string): Promise<string[]> {
  const entries = await fs.readdir(dir, { withFileTypes: true })
  const nested = await Promise.all(
    entries.map(async (entry) => {
      const fullPath = path.join(dir, entry.name)

      if (entry.isDirectory()) {
        if (IGNORED_DIRS.has(entry.name)) return []
        return scanDirectory(fullPath)
      }

      if (!entry.isFile()) return []
      if (!/\.(ts|tsx|json|md|mdx)$/.test(entry.name)) return []
      if (isGeneratedFile(fullPath)) return []
      return [fullPath]
    }),
  )

  return nested.flat()
}

async function scanSourceFiles(): Promise<string[]> {
  const roots = await Promise.all(
    SCAN_ROOTS.map(async (root) => {
      const rootPath = path.join(ROOT_DIR, root)
      if (!(await pathExists(rootPath))) return []
      return scanDirectory(rootPath)
    }),
  )

  return [...new Set(roots.flat())].sort()
}

function lineOf(source: ts.SourceFile, position: number): number {
  return source.getLineAndCharacterOfPosition(position).line + 1
}

function nodeText(source: ts.SourceFile, node: ts.Node): string {
  return source.text.slice(node.getFullStart(), node.getEnd()).trim()
}

function collectImports(source: ts.SourceFile): string[] {
  return source.statements
    .filter(ts.isImportDeclaration)
    .map((statement) => statement.getText(source).replace(/\s+/g, ' ').trim())
}

function nameOf(name: ts.PropertyName | ts.BindingName | undefined): string {
  if (!name) return 'default'
  if (ts.isIdentifier(name) || ts.isPrivateIdentifier(name)) return name.text
  if (ts.isStringLiteral(name) || ts.isNumericLiteral(name)) return name.text
  if (ts.isComputedPropertyName(name)) return name.getText()
  if (ts.isObjectBindingPattern(name) || ts.isArrayBindingPattern(name)) return name.getText()
  return 'anonymous'
}

function isExported(node: ts.Node): boolean {
  return ts.canHaveModifiers(node) && Boolean(ts.getModifiers(node)?.some((m) => m.kind === ts.SyntaxKind.ExportKeyword))
}

function isPascalCase(value: string): boolean {
  return /^[A-Z][A-Za-z0-9_$]*$/.test(value)
}

function isHookName(value: string): boolean {
  return /^use[A-Z0-9]/.test(value)
}

function classifyFunctionLike(name: string, sourceText: string): ChunkType {
  if (isHookName(name)) return 'hook'
  if (isPascalCase(name) || /<[A-Z][A-Za-z0-9_$]*[\s>]/.test(sourceText)) return 'component'
  return 'function'
}

function classifyVariable(statement: ts.VariableStatement, declaration: ts.VariableDeclaration): ChunkType {
  const name = nameOf(declaration.name)
  const initializer = declaration.initializer
  if (initializer && (ts.isArrowFunction(initializer) || ts.isFunctionExpression(initializer))) {
    return classifyFunctionLike(name, initializer.getText())
  }
  if (isHookName(name)) return 'hook'
  if (isPascalCase(name)) return 'component'
  if (isExported(statement)) return 'const'
  return 'const'
}

function addChunk(
  chunks: CodeChunk[],
  source: ts.SourceFile,
  node: ts.Node,
  symbolName: string,
  chunkType: ChunkType,
  imports: string[],
): void {
  const content = nodeText(source, node)
  if (!content) return

  chunks.push({
    content,
    startLine: lineOf(source, node.getFullStart()),
    endLine: lineOf(source, node.getEnd()),
    symbolName,
    chunkType,
    language: 'typescript',
    imports,
  })
}

function objectMethodName(parentName: string, name: string): string {
  return parentName ? `${parentName}.${name}` : name
}

function hasFunctionLikeValue(node: ts.ObjectLiteralElementLike): boolean {
  if (ts.isMethodDeclaration(node)) return true
  if (!ts.isPropertyAssignment(node)) return false
  const value = node.initializer
  return ts.isArrowFunction(value) || ts.isFunctionExpression(value)
}

function collectObjectMethodChunks(
  chunks: CodeChunk[],
  source: ts.SourceFile,
  root: ts.Node,
  parentName: string,
  imports: string[],
): void {
  function visit(node: ts.Node): void {
    if (ts.isObjectLiteralExpression(node)) {
      for (const property of node.properties) {
        if (!hasFunctionLikeValue(property)) continue
        const propertyName = nameOf(property.name)
        addChunk(chunks, source, property, objectMethodName(parentName, propertyName), 'object_method', imports)
      }
    }

    ts.forEachChild(node, visit)
  }

  ts.forEachChild(root, visit)
}

function chunkTypeScriptFile(filePath: string, content: string): CodeChunk[] {
  const kind = filePath.endsWith('.tsx') ? ts.ScriptKind.TSX : ts.ScriptKind.TS
  const source = ts.createSourceFile(filePath, content, ts.ScriptTarget.Latest, true, kind)
  const imports = collectImports(source)
  const chunks: CodeChunk[] = []
  const coveredStatements = new Set<ts.Statement>()

  for (const statement of source.statements) {
    if (ts.isFunctionDeclaration(statement)) {
      const symbolName = nameOf(statement.name)
      addChunk(chunks, source, statement, symbolName, classifyFunctionLike(symbolName, statement.getText()), imports)
      collectObjectMethodChunks(chunks, source, statement, symbolName, imports)
      coveredStatements.add(statement)
      continue
    }

    if (ts.isClassDeclaration(statement)) {
      const symbolName = nameOf(statement.name)
      addChunk(chunks, source, statement, symbolName, 'class', imports)
      coveredStatements.add(statement)
      continue
    }

    if (
      ts.isInterfaceDeclaration(statement) ||
      ts.isTypeAliasDeclaration(statement) ||
      ts.isEnumDeclaration(statement)
    ) {
      const symbolName = nameOf(statement.name)
      addChunk(chunks, source, statement, symbolName, 'type', imports)
      coveredStatements.add(statement)
      continue
    }

    if (ts.isVariableStatement(statement)) {
      for (const declaration of statement.declarationList.declarations) {
        const symbolName = nameOf(declaration.name)
        addChunk(chunks, source, statement, symbolName, classifyVariable(statement, declaration), imports)
        if (declaration.initializer) {
          collectObjectMethodChunks(chunks, source, declaration.initializer, symbolName, imports)
        }
      }
      coveredStatements.add(statement)
      continue
    }
  }

  let pendingStart: number | null = null
  let pendingEnd: number | null = null
  for (const statement of source.statements) {
    if (coveredStatements.has(statement)) {
      if (pendingStart !== null && pendingEnd !== null) {
        addLooseChunk(chunks, source, pendingStart, pendingEnd, imports)
      }
      pendingStart = null
      pendingEnd = null
      continue
    }

    pendingStart ??= statement.getFullStart()
    pendingEnd = statement.getEnd()
  }

  if (pendingStart !== null && pendingEnd !== null) {
    addLooseChunk(chunks, source, pendingStart, pendingEnd, imports)
  }

  return chunks.flatMap(splitLargeChunk)
}

function addLooseChunk(chunks: CodeChunk[], source: ts.SourceFile, start: number, end: number, imports: string[]): void {
  const content = source.text.slice(start, end).trim()
  if (!content) return
  chunks.push({
    content,
    startLine: lineOf(source, start),
    endLine: lineOf(source, end),
    symbolName: '(module)',
    chunkType: 'file',
    language: 'typescript',
    imports,
  })
}

function splitLargeChunk(chunk: CodeChunk): CodeChunk[] {
  if (chunk.content.length <= MAX_CHUNK_CHARS) return [chunk]

  const lines = chunk.content.split(/\r?\n/)
  const chunks: CodeChunk[] = []
  let start = 0

  while (start < lines.length) {
    let end = start
    let charCount = 0

    while (end < lines.length && charCount + lines[end].length + 1 <= MAX_CHUNK_CHARS) {
      charCount += lines[end].length + 1
      end += 1
    }

    if (end === start) end += 1

    const content = lines.slice(start, end).join('\n').trim()
    if (content) {
      chunks.push({
        ...chunk,
        content,
        symbolName: chunks.length === 0 ? chunk.symbolName : `${chunk.symbolName}#${chunks.length}`,
        startLine: chunk.startLine + start,
        endLine: chunk.startLine + end - 1,
      })
    }

    if (end >= lines.length) break
    start = Math.max(end - OVERLAP_LINES, start + 1)
  }

  return chunks
}

function chunkJsonFile(filePath: string, content: string): CodeChunk[] {
  try {
    const parsed = JSON.parse(content) as unknown
    if (Array.isArray(parsed)) return chunkJsonArray(path.basename(filePath), parsed, content)
    if (parsed && typeof parsed === 'object') return chunkJsonObject(parsed as Record<string, unknown>, content)
  } catch {
    // Fall back to text splitting below.
  }

  return splitTextAsJson(content, path.basename(filePath))
}

function chunkJsonObject(objectValue: Record<string, unknown>, rawContent: string): CodeChunk[] {
  const chunks: CodeChunk[] = []
  for (const [key, value] of Object.entries(objectValue)) {
    const serialized = JSON.stringify({ [key]: value }, null, 2)
    chunks.push(...splitTextAsJson(serialized, key, rawContent.indexOf(`"${key}"`)))
  }
  return chunks.length > 0 ? chunks : splitTextAsJson(rawContent, 'json')
}

function chunkJsonArray(symbolName: string, values: unknown[], rawContent: string): CodeChunk[] {
  const chunks: CodeChunk[] = []
  let current: unknown[] = []
  let currentStart = 0

  for (let i = 0; i < values.length; i += 1) {
    current.push(values[i])
    const serialized = JSON.stringify(current, null, 2)
    if (serialized.length >= MAX_CHUNK_CHARS) {
      chunks.push(jsonChunk(`${symbolName}[${currentStart}-${i}]`, serialized, 1, lineCount(rawContent)))
      current = []
      currentStart = i + 1
    }
  }

  if (current.length > 0) {
    chunks.push(
      jsonChunk(
        `${symbolName}[${currentStart}-${values.length - 1}]`,
        JSON.stringify(current, null, 2),
        1,
        lineCount(rawContent),
      ),
    )
  }

  return chunks
}

function splitTextAsJson(content: string, symbolName: string, offset = 0): CodeChunk[] {
  const lines = content.split(/\r?\n/)
  const chunks: CodeChunk[] = []
  let start = 0

  while (start < lines.length) {
    let end = start
    let charCount = 0

    while (end < lines.length && charCount + lines[end].length + 1 <= MAX_CHUNK_CHARS) {
      charCount += lines[end].length + 1
      end += 1
    }

    if (end === start) end += 1
    chunks.push(jsonChunk(symbolName, lines.slice(start, end).join('\n'), lineFromOffset(content, offset) + start, lineFromOffset(content, offset) + end - 1))
    if (end >= lines.length) break
    start = Math.max(end - OVERLAP_LINES, start + 1)
  }

  return chunks
}

function jsonChunk(symbolName: string, content: string, startLine: number, endLine: number): CodeChunk {
  return {
    content,
    startLine,
    endLine,
    symbolName,
    chunkType: 'json',
    language: 'json',
  }
}

function lineCount(content: string): number {
  return content.split(/\r?\n/).length
}

function lineFromOffset(content: string, offset: number): number {
  if (offset <= 0) return 1
  return content.slice(0, offset).split(/\r?\n/).length
}

function chunkMarkdownFile(filePath: string, content: string): CodeChunk[] {
  const lines = content.split(/\r?\n/)
  const chunks: CodeChunk[] = []
  let start = 0

  for (let i = 1; i < lines.length; i += 1) {
    if (/^#{1,3}\s+/.test(lines[i])) {
      const block = lines.slice(start, i).join('\n').trim()
      if (block) {
        chunks.push({
          content: block,
          startLine: start + 1,
          endLine: i,
          symbolName: headingName(lines[start]) || path.basename(filePath),
          chunkType: 'file',
          language: 'markdown',
        })
      }
      start = i
    }
  }

  const finalBlock = lines.slice(start).join('\n').trim()
  if (finalBlock) {
    chunks.push({
      content: finalBlock,
      startLine: start + 1,
      endLine: lines.length,
      symbolName: headingName(lines[start]) || path.basename(filePath),
      chunkType: 'file',
      language: 'markdown',
    })
  }

  return chunks.flatMap(splitLargeChunk)
}

function headingName(line: string | undefined): string | null {
  const match = line?.match(/^#{1,6}\s+(.+)$/)
  return match?.[1]?.trim() ?? null
}

function inferFileSummary(filePath: string, chunks: CodeChunk[]): string {
  const projectPath = toProjectPath(filePath)
  const symbols = chunks
    .filter((chunk) => chunk.chunkType !== 'summary')
    .map((chunk) => chunk.symbolName)
    .filter((name) => name && name !== '(module)')
    .slice(0, 12)
  const types = [...new Set(chunks.map((chunk) => chunk.chunkType).filter((type) => type !== 'summary'))]
  const hints = projectPath
    .replace(/\.(tsx?|json|mdx?)$/, '')
    .split(/[\/_.-]+/)
    .filter(Boolean)
    .slice(-5)

  return [
    `File summary for ${projectPath}.`,
    hints.length > 0 ? `Path context: ${hints.join(', ')}.` : '',
    types.length > 0 ? `Contains ${types.join(', ')} chunks.` : '',
    symbols.length > 0 ? `Key symbols: ${symbols.join(', ')}.` : '',
  ].filter(Boolean).join(' ')
}

function addFileSummaryChunk(filePath: string, chunks: CodeChunk[], content: string): CodeChunk[] {
  const summary: CodeChunk = {
    content: inferFileSummary(filePath, chunks),
    startLine: 1,
    endLine: Math.max(1, lineCount(content)),
    symbolName: '(file_summary)',
    chunkType: 'summary',
    language: filePath.endsWith('.json') ? 'json' : /\.(md|mdx)$/.test(filePath) ? 'markdown' : 'typescript',
    imports: chunks.find((chunk) => chunk.imports?.length)?.imports,
  }

  return [summary, ...chunks]
}

function chunkFile(filePath: string, content: string): CodeChunk[] {
  const chunks = filePath.endsWith('.json')
    ? chunkJsonFile(filePath, content)
    : /\.(md|mdx)$/.test(filePath)
    ? chunkMarkdownFile(filePath, content)
    : chunkTypeScriptFile(filePath, content)

  return addFileSummaryChunk(filePath, chunks, content)
}

async function readJson<T>(filePath: string, fallback: T): Promise<T> {
  try {
    return JSON.parse(await fs.readFile(filePath, 'utf8')) as T
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return fallback
    throw error
  }
}

async function writeJson(filePath: string, value: unknown): Promise<void> {
  await fs.mkdir(path.dirname(filePath), { recursive: true })
  const tmpPath = `${filePath}.tmp`
  await fs.writeFile(tmpPath, `${JSON.stringify(value, null, 2)}\n`, 'utf8')
  await fs.rename(tmpPath, filePath)
}

async function loadSyncState(): Promise<SyncState> {
  return readJson<SyncState>(SYNC_STATE_PATH, { version: 1, files: {} })
}

async function embedText(text: string): Promise<number[]> {
  const response = await fetch(`${OLLAMA_URL}/api/embeddings`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: OLLAMA_EMBED_MODEL,
      prompt: text,
    }),
  })

  if (!response.ok) {
    const body = await response.text()
    throw new Error(`Ollama embedding failed (${response.status}): ${body}`)
  }

  const data = (await response.json()) as { embedding?: number[] }
  if (!Array.isArray(data.embedding)) {
    throw new Error(`Ollama response did not include an embedding. Is "${OLLAMA_EMBED_MODEL}" installed?`)
  }

  return data.embedding
}

function embeddingInput(filePath: string, chunk: CodeChunk): string {
  return [
    `File: ${filePath}`,
    `Symbol: ${chunk.symbolName}`,
    `Type: ${chunk.chunkType}`,
    `Lines: ${chunk.startLine}-${chunk.endLine}`,
    `Language: ${chunk.language}`,
    '',
    chunk.content,
  ].join('\n')
}

async function connectDb(): Promise<any> {
  await fs.mkdir(LANCEDB_DIR, { recursive: true })
  return lancedb.connect(LANCEDB_DIR)
}

async function tableExists(db: any): Promise<boolean> {
  const names = await db.tableNames()
  return names.includes(TABLE_NAME)
}

function escapeSqlString(value: string): string {
  return value.replace(/'/g, "''")
}

async function openCodeTable(db: any): Promise<any | null> {
  if (!(await tableExists(db))) return null
  return db.openTable(TABLE_NAME)
}

async function upsertRecords(db: any, records: LanceCodeRecord[]): Promise<void> {
  if (records.length === 0) return

  const existing = await openCodeTable(db)
  if (!existing) {
    await db.createTable(TABLE_NAME, records)
    return
  }

  await existing.add(records)
}

async function deleteFileChunks(db: any, filePath: string): Promise<void> {
  const table = await openCodeTable(db)
  if (!table) return
  await table.delete(`file_path = '${escapeSqlString(filePath)}'`)
}

export async function indexCodebase(): Promise<void> {
  const db = await connectDb()
  const syncState = await loadSyncState()
  const sourceFiles = await scanSourceFiles()
  const seenFiles = new Set<string>()

  let indexedFiles = 0
  let skippedFiles = 0
  let indexedChunks = 0

  for (const absolutePath of sourceFiles) {
    const projectPath = toProjectPath(absolutePath)
    seenFiles.add(projectPath)

    const content = await fs.readFile(absolutePath, 'utf8')
    if (isGeneratedFile(absolutePath, content)) continue

    const fileHash = sha256(content)
    const previous = syncState.files[projectPath]

    if (previous?.hash === fileHash) {
      skippedFiles += 1
      continue
    }

    await deleteFileChunks(db, projectPath)

    const chunks = chunkFile(absolutePath, content)
    const records: LanceCodeRecord[] = []

    for (let chunkIndex = 0; chunkIndex < chunks.length; chunkIndex += 1) {
      const chunk = chunks[chunkIndex]
      const vector = await embedText(embeddingInput(projectPath, chunk))
      records.push({
        id: `${projectPath}:${fileHash}:${chunkIndex}`,
        vector,
        file_path: projectPath,
        file_hash: fileHash,
        chunk_index: chunkIndex,
        language: chunk.language,
        start_line: chunk.startLine,
        end_line: chunk.endLine,
        symbol_name: chunk.symbolName,
        chunk_type: chunk.chunkType,
        imports: chunk.imports?.join('\n') ?? '',
        content: chunk.content,
      })
    }

    await upsertRecords(db, records)

    syncState.files[projectPath] = {
      hash: fileHash,
      chunkIds: records.map((record) => record.id),
      indexedAt: new Date().toISOString(),
    }

    indexedFiles += 1
    indexedChunks += records.length
    console.log(`Indexed ${projectPath} (${records.length} chunks)`)
  }

  for (const indexedPath of Object.keys(syncState.files)) {
    if (seenFiles.has(indexedPath)) continue
    await deleteFileChunks(db, indexedPath)
    delete syncState.files[indexedPath]
    console.log(`Removed deleted file from index: ${indexedPath}`)
  }

  await writeJson(SYNC_STATE_PATH, syncState)
  console.log(
    `Done. Indexed ${indexedFiles} changed files (${indexedChunks} chunks), skipped ${skippedFiles} unchanged files.`,
  )
}

function looksLikeIdentifierQuery(query: string): boolean {
  const trimmed = query.trim()
  if (!trimmed) return false
  if (!trimmed.includes(' ')) return true
  return /[A-Za-z_$][\w$]*(\.[A-Za-z_$][\w$]*)?/.test(trimmed) && trimmed.split(/\s+/).length <= 3
}

function keywordScore(row: Record<string, unknown>, query: string, identifierMode: boolean): number {
  const needle = query.toLowerCase()
  const terms = needle.split(/\s+/).filter(Boolean)
  const symbol = String(row.symbol_name ?? '').toLowerCase()
  const imports = String(row.imports ?? '').toLowerCase()
  const content = String(row.content ?? '').toLowerCase()
  const filePath = String(row.file_path ?? '').toLowerCase()

  let score = 0
  if (symbol === needle) score += 100
  if (symbol.includes(needle)) score += 60
  if (filePath.includes(needle)) score += 35
  if (imports.includes(needle)) score += 25
  if (content.includes(needle)) score += identifierMode ? 45 : 20

  for (const term of terms) {
    if (term.length < 2) continue
    if (symbol.includes(term)) score += 12
    if (filePath.includes(term)) score += 8
    if (imports.includes(term)) score += 6
    if (content.includes(term)) score += 4
  }

  return score
}

function calculateScore(row: Record<string, unknown>, query: string, baseScore: number): number {
  const symbol = String(row.symbol_name ?? '')
  const chunkType = String(row.chunk_type ?? '')
  const content = String(row.content ?? '')
  let score = baseScore

  if (symbol === query) score += 10_000

  if (['function', 'component', 'type', 'interface', 'hook', 'object_method'].includes(chunkType)) {
    score += 250
  }

  const nonEmptyLines = content.split(/\r?\n/).map((line) => line.trim()).filter(Boolean)
  const importLines = nonEmptyLines.filter((line) => line.startsWith('import ') || line.startsWith('export {'))
  const mostlyImports = nonEmptyLines.length > 0 && importLines.length / nonEmptyLines.length >= 0.6

  if (chunkType === 'file' || chunkType === 'module' || mostlyImports) {
    score -= 300
  }

  return score
}

async function keywordSearch(table: any, query: string, limit: number): Promise<CodeSearchResult[]> {
  const rows = (await table.toArrow()).toArray() as Record<string, unknown>[]
  const identifierMode = looksLikeIdentifierQuery(query)

  return rows
    .map((row) => ({ row, score: calculateScore(row, query, keywordScore(row, query, identifierMode)) }))
    .filter((item) => item.score > 0)
    .sort((a, b) => b.score - a.score)
    .slice(0, identifierMode ? limit : Math.min(3, limit))
    .map(({ row, score }) => rowToSearchResult(row, 'keyword', score))
}

async function vectorSearch(table: any, query: string, limit: number): Promise<CodeSearchResult[]> {
  const queryVector = await embedText(query)
  const rows = (await table.search(queryVector).limit(VECTOR_CANDIDATE_LIMIT).toArray()) as Record<string, unknown>[]

  return rows
    .map((row) => {
      const distance = typeof row._distance === 'number' ? row._distance : 0
      return rowToSearchResult(row, 'vector', calculateScore(row, query, 1_000 - distance))
    })
    .sort((a, b) => b.score - a.score)
    .slice(0, limit)
}

function rowKey(result: Pick<CodeSearchResult, 'file_path' | 'chunk_index'>): string {
  return `${result.file_path}:${result.chunk_index}`
}

function rowToSearchResult(
  row: Record<string, unknown>,
  source: CodeSearchResult['source'],
  score: number,
): CodeSearchResult {
  return {
    score,
    source,
    file_path: String(row.file_path),
    start_line: Number(row.start_line),
    end_line: Number(row.end_line),
    chunk_index: Number(row.chunk_index),
    symbol_name: String(row.symbol_name ?? '(unknown)'),
    chunk_type: String(row.chunk_type ?? 'file') as ChunkType,
    imports: String(row.imports ?? '').split('\n').filter(Boolean),
    content: String(row.content),
  }
}

export async function searchCodebase(query: string, limit = SEARCH_LIMIT): Promise<CodeSearchResult[]> {
  const db = await connectDb()
  const table = await openCodeTable(db)
  if (!table) {
    throw new Error('No LanceDB code index found. Run `npm run code-index` first.')
  }

  const exactMatches = await keywordSearch(table, query, limit)
  const vectorMatches = await vectorSearch(table, query, limit)
  const seen = new Set<string>()
  const combined: CodeSearchResult[] = []

  for (const result of [...exactMatches, ...vectorMatches]) {
    const key = rowKey(result)
    if (seen.has(key)) continue
    seen.add(key)
    combined.push(result)
    if (combined.length >= limit) break
  }

  return combined
}

function preview(content: string): string {
  const lines = content.trim().split(/\r?\n/)
  const clipped = lines.slice(0, 18).join('\n')
  return lines.length > 18 ? `${clipped}\n...` : clipped
}

async function runCli(): Promise<void> {
  const [, , command = 'index', ...args] = process.argv

  if (command === 'index') {
    await indexCodebase()
    return
  }

  if (command === 'search') {
    const query = args.join(' ').trim()
    if (!query) throw new Error('Usage: npm run code-search -- "where is multiplayer turn logic handled?"')

    const results = await searchCodebase(query)
    for (const result of results) {
      const scoreLabel = result.source === 'vector' ? 'distance' : 'keyword'
      console.log(
        `\n${result.file_path}:${result.start_line}-${result.end_line} ` +
          `[${result.chunk_type} ${result.symbol_name}] ${result.source} ${scoreLabel}=${result.score.toFixed(4)}`,
      )
      console.log(preview(result.content))
    }
    return
  }

  throw new Error(`Unknown command "${command}". Use "index" or "search".`)
}

if (import.meta.url === `file://${process.argv[1]}`) {
  runCli().catch((error) => {
    console.error(error instanceof Error ? error.message : error)
    process.exitCode = 1
  })
}
