// Generated by scripts/fetch-words.mjs — do not edit by hand.
// Run `node scripts/fetch-words.mjs` to refresh from the TDK word list.
import tdkWords from './tdk-words.json'

// Each entry is [word, corpusCount]
export const WORD_LISTS: Record<number, [string, number][]> = tdkWords as unknown as Record<number, [string, number][]>
